config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  get '/genre_search' => 'search#genre_search'

  devise_for :users

  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :articles do
    resource :favorites, only: [:create, :destroy]
    resources :article_comments, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :myindex, on: :member, to: 'articles#myindex'
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'sessions#new_guest'
  end
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :article

  # バリデーション
  validates :comment, presence: true
end

app/controllers/article_comments_controller.rb
class ArticleCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    @comment = ArticleComment.new(article_comment_params)
    @comment.user_id = current_user.id
    @comment.article_id = @article.id
    unless @comment.save
      render 'error' # comments/error.js.erbを呼び出す
    end
  end

  def destroy
    ArticleComment.find_by(id: params[:id], article_id: params[:article_id]).destroy
    @article = Article.find(params[:article_id])
  end

  private

  def article_comment_params
    params.require(:article_comment).permit(:comment)
  end
end

app/helpers/article_comments_helper.rb
module ArticleCommentsHelper
end

app/views/article_comments/_article_comments.html.erb
  <table class="article-comment">
  <% article.article_comments.each do |article_comment| %>
    <tr>
      <td class="fas fa-user">
        <%= link_to user_path(article_comment.user) do %>
          <%= article_comment.user.name %>
        <% end %>
      </td>
      <td class="far fa-comments">
        <%= article_comment.comment %>
      </td>
      <td>
        <% if article_comment.user == current_user %>
          <%= link_to "削除", article_article_comment_path(article_comment.article, article_comment), method: :delete, remote: true, class: "btn btn-outline-primary" %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </table>

app/views/article_comments/create.js.erb
$("#article_<%= @article.id %> .comments-count").html("コメント数: <%= @article.article_comments.count %>");
$(".comment-index").html("<%= j(render 'article_comments', article: @article) %>");
$("textarea").val('')

app/views/article_comments/destroy.js.erb
$(".comment-index").html("<%= j(render 'article_comments', article: @article) %>");

app/views/article_comments/error.js.erb
$("#comments_error").html("<%= j(render 'layouts/error_messages', obj: @comment) %>");