config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  get '/genre_search' => 'search#genre_search'

  devise_for :users

  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :articles do
    resource :favorites, only: [:create, :destroy]
    resources :article_comments, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :myindex, on: :member, to: 'articles#myindex'
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'sessions#new_guest'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  # アソシエーション
  belongs_to :user
  attachment :image
  has_many:article_comments, dependent: :destroy
  has_many:favorites, dependent: :destroy
  belongs_to :genre, optional: true

  # 公開・非公開設定
  enum status: { 公開: 0, 非公開: 1 }

  # バリデーション
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  #いいねランキング
  def self.favorite_ranking
    today = Time.zone.today
    articles = Article.where(start_time: today.beginning_of_month..today.end_of_month)
    article_ids = Favorite.
      where(article_id: articles.pluck(:id)).
      group(:article_id).
      order('count(article_id) desc').limit(5).pluck(:article_id)
    Article.find(article_ids)
  end

  def self.fevorite_ranking_onemonths
    one_months_ago = 1.months.ago
    one_months_ago_articles = Article.where(start_time: one_months_ago.beginning_of_month..one_months_ago.end_of_month)
    one_months_ago_article_ids = Favorite.
      where(article_id: one_months_ago_articles.pluck(:id)).
      group(:article_id).
      order('count(article_id) desc').limit(5).pluck(:article_id)
    Article.find(one_months_ago_article_ids)  
  end


end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :article

  # バリデーション
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :article
end

app/models/genre.rb
class Genre < ApplicationRecord
  # アソシエーション
  has_many :articles
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # アソシエーション
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:articles, dependent: :destroy
  has_many:article_comments, dependent: :destroy
  has_many:favorites, dependent: :destroy

  # 自分がフォローしているユーザーとの関連
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  # 自分がフォローされるユーザーとの関連
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!

  def new
    @article = Article.new
    @genres = Genre.all
    @articles = Article.page(params[:page]).reverse_order
  end

  def create
    @genres = Genre.all
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @article.score = Language.get_data(article_params[:body])
    @article.save
    # start_timeはcreateされた日時を指すため、create後に確定される
    if @article.update(start_time: @article.created_at)
      flash[:notice] = "投稿が成功しました!!"
      redirect_to articles_path
    else
      @genres = Genre.all
      @articles = Article.page(params[:page]).reverse_order
      render :new
    end
  end

  def index
    @articles = Article.where(status: 0).page(params[:page]).reverse_order
    @genres = Genre.all
    # 当月いいねランキング
    @all_ranks = Article.favorite_ranking
    # 前月いいねランキング
    @one_months_ago_ranks = Article.fevorite_ranking_onemonths
  end

  def show
    @article = Article.find(params[:id])
    @article_comment = ArticleComment.new
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
    @genres = Genre.all
  end

  def update
    @genres = Genre.all
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "編集に成功しました"
      redirect_to article_path(@article.id)
    else
      render :edit
    end
  end

  def myindex
    @user = User.find(params[:id])
    @genres = Genre.all

    # 表示の条件（公開・非公開）
    if @user.id == current_user.id
      @articles = Article.where(user_id: @user.id).page(params[:page]).reverse_order
    else
      @articles = Article.where(status: 0, user_id: @user.id).page(params[:page]).reverse_order
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :image, :genre_id, :start_time, :status)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    favorite = current_user.favorites.new(article_id: @article.id)
    favorite.save
  end

  def destroy
    @article = Article.find(params[:article_id])
    favorite = current_user.favorites.find_by(article_id: @article.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  # キーワード検索
  def search
    @genres = Genre.all
    search_word = params[:search][:keyword]
    if search_word
      @articles = Article.where(['body LIKE ?', "%#{search_word}%"]).page(params[:page]).reverse_order
    else
      @articles = Article.all
    end
  end

  # ジャンル検索
  def genre_search
    genre_id = params[:search][:value]
    @articles = Article.where(genre_id: genre_id).page(params[:page]).reverse_order
    @genres = Genre.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # ゲストユーザー作成
  def new_guest
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @articles = @user.articles
    @article = Article.new
    @genres = Genre.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
    # 当月いいねランキング
    @all_ranks = Article.favorite_ranking
    # 先月いいねランキング
    @one_months_ago_ranks = Article.fevorite_ranking_onemonths
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_comments_helper.rb
module ArticleCommentsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_genre_search.html.erb
<div class="card my-4">
  <h5 class="card-header">ジャンル検索</h5>
  <div class="card-body">
    <% @genres.each do |genre| %>
		<span>
      <%= link_to genre.name, genre_search_path('search[value]': genre.id) %>
		</span>
		<% end %>
	</div>
</div>

<div class="card my-4">
    <h5 class="card-header">キーワード検索</h5>
    <div class="card-body">
    <%= form_with url: search_path, method: :get, local: true do |f| %>
    	<div class="input-group">
		  <%= f.text_field 'search[keyword]', size: "26x4", placeholder: 'キーワードから探す' %><br>
      <%= f.submit :"検索", class: "btn btn-outline-secondary mt-2" %>
      </div>
    <% end %>
	  </div>
</div>

app/views/articles/_ranking.html.erb
<div class="card my-4">
  <h5 class="card-header">今月のいいねランキング</h5>
  <div class="card-body">
  <% all_ranks.each.with_index(1) do |article, i| %>
    <div class="ranking-text">
  	    <strong class="ranking-nunmer">第<%= i %>位</strong>
  	    <div class="ranking-body">
          <div><i class="fas fa-heart"></i>：<%= article.favorites.count %></div>
          <div><i class="fas fa-user"></i>：<%= article.user.name %></div>
          <div><i class="fas fa-book-open"></i>：
          <%= link_to article_path(article) do %>
            <%= article.title %>
          <% end %></div>
        </div>
    </div>
  <% end %>
	</div>
</div>

<div class="card my-4">
  <h5 class="card-header">先月のいいねランキング</h5>
  <div class="card-body">
  <% one_months_ago_ranks.each.with_index(1) do |article, i| %>
    <div class="ranking-text">
  	  <strong class="ranking-nunmer">第<%= i %>位</strong>
      <div class="ranking-body">
        <div><i class="fas fa-heart"></i>：<%= article.favorites.count %></div>
        <div><i class="fas fa-user"></i>：<%= article.user.name %></div>
        <div><i class="fas fa-book-open"></i>：
        <%= link_to article_path(article) do %>
          <%= article.title %>
        <% end %></div>
      </div>
    </div>
  <% end %>
	</div>
</div>

app/views/articles/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-12 offset-md-1 mt-5">
      <h2><i class="fas fa-edit"></i>投稿記事編集</h2>
      <div class="col-10 edit-form">
        <%= render 'layouts/error_messages', obj: @article %>
        <%= notice %>
        <%= form_with model: @article, local:true do |f| %>
        <div class="row">
          <div class="col-md">
            <form>
              <div class="form-group">
                <label><i class="fas fa-hand-point-right"></i>タイトル</label>
                <%= f.text_field :title, class: "form-control" %>
              </div>
              <div class="form-group">
                <label><i class="fas fa-hand-point-right"></i>画像</label>
                <p><%= f.attachment_field :image %></p>
              </div>
              <div class="form-group">
                <label><i class="fas fa-hand-point-right"></i>本文</label>
                <%= f.text_area :body, class: "form-control" %>
              </div>
              <div class="form-group">
                <label><i class="fas fa-hand-point-right"></i>ジャンル選択</label>
                <p><%= f.collection_select(:genre_id, @genres, :id, :name) %></p>
              </div>
              <div class="form-group">
                <label><i class="fas fa-hand-point-right"></i>公開・非公開設定</label>
                <p><%= f.select :status,[["公開", "公開"],["非公開", "非公開"]] %></p>
              </div>
              <%= f.submit '保存', class: "btn btn-outline-success btn-lg btn-block mt-4 mb-4" %>
        <% end %>
            </form>
      </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3 mt-5">
      <%= render 'articles/genre_search', genres: @genres %>
      <%= render 'articles/ranking', all_ranks: @all_ranks, one_months_ago_ranks: @one_months_ago_ranks %>
    </div>

    <div class="col-md-8 offset-md-1 mt-5">
      <h2><i class="fas fa-book-open"></i>投稿一覧</h2>
      <div class="col-10">
        <% @articles.each do |article| %>
        <div class="card">
          <h5 class="card-header">
            <%= link_to article_path(article.id) do %>
              <%= article.title %>
            <% end %>
            <span class="float-right"><small class="fas fa-user">
              <%= link_to user_path(article.user) do %>
                <%= article.user.name %>
              <% end %> </small>
            </span></h5>
            <div class="card-body">
              <p class="card-text small_line_wrap"><%= article.body %></p>
              <span class="sentiment-score">本文の感情分析スコア<%= article.score %></span>
              <div class="d-flex justify-content-end">
                <div class="pt-1 mr-2">
                  <small>投稿日:<%= article.created_at.strftime('%m/%d') %></small>
                  <i class="favorite-btn_<%= article.id %>"><%= render 'favorites/favorites', article: article %></i>
                  <i class="far fa-comments ml-1"></i>
                  <%= article.article_comments.count %>
                </div>
              </div>
            </div>
        </div>
        <% end %>
        <%= paginate @articles %>
      </div>
    </div>
  </div>
</div>

app/views/articles/myindex.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3 mt-5">
      <%= render 'articles/genre_search', genres: @genres %>
    </div>

    <div class="col-md-8 offset-md-1 mt-5">
      <h2><i class="fas fa-book-open"></i><%= @user.name %>の投稿一覧</h2>
      <div class="col-10">
        <% @articles.each do |article| %>
        <div class="card">
          <h5 class="card-header">
            <%= link_to article_path(article.id) do %>
              <%= article.title %>
            <% end %>
            <span class="float-right"><small class="fas fa-user">
              <%= link_to user_path(article.user) do %>
                <%= article.user.name %>
              <% end %> </small>
            </span></h5>
            <div class="card-body">
              <p class="card-text small_line_wrap"><%= article.body %></p>
              <div class="d-flex justify-content-end">
                <div class="pt-1 mr-2">
                  <small>投稿日:<%= article.created_at.strftime('%m/%d') %></small>
                  <i class="favorite-btn_<%= article.id %>"><%= render 'favorites/favorites', article: article %></i>
                  <i class="far fa-comments ml-1"></i>
                  <%= article.article_comments.count %>
                </div>
              </div>
            </div>
        </div>
        <% end %>
        <%= paginate @articles %>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3 mt-5">
      <%= render 'articles/genre_search', genres: @genres %>
    </div>

    <div class="col-md-8 offset-md-1 mt-5">
      <h2><i class="fas fa-edit"></i>新規投稿</h2>
      <div class="col-10 new-form">
        <%= render 'layouts/error_messages', obj: @article %>
        <%= form_with model: @article, local:true do |f| %>
        <div class="row">
          <div class="col-md">
            <form>
              <div class="form-group">
                <label><i class="fas fa-hand-point-right"></i>タイトル</label>
                <%= f.text_field :title, class: "form-control" %>
              </div>
              <div class="form-group">
                <label><i class="fas fa-hand-point-right"></i>画像</label>
                <p><%= f.attachment_field :image %></p>
              </div>
              <div class="form-group">
                <label><i class="fas fa-hand-point-right"></i>本文</label>
                <%= f.text_area :body, class: "form-control" %>
              </div>
              <div class="form-group">
                <label><i class="fas fa-hand-point-right"></i>ジャンル選択</label>
                <p><%= f.collection_select(:genre_id, @genres, :id, :name) %></p>
              </div>
              <div class="form-group">
                <label><i class="fas fa-hand-point-right"></i>公開・非公開設定</label>
                <p><%= f.select :status,[["公開", "公開"],["非公開", "非公開"]] %></p>
              </div>
              <%= f.submit '投稿', class: "btn btn-outline-success btn-lg btn-block mt-4 mb-4" %>
        <% end %>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
  	<div class="col-9 bg-white rounded article-show">
  	  <div class="success_messages">
    	  <%= notice %>
    	 </div>
  		<h4 class="mt-4"><%= @article.title %>
  		<span class="float-right"><small class="fas fa-user">
        <%= link_to user_path(@article.user) do %>
          <%= @article.user.name %>
        <% end %> </small>
      </span></h4>
        <div class="article-text">
          <p><%= attachment_image_tag @article, :image, size:'300x300' %></p>
          <p><%= @article.body %></p>

          <div class="d-flex justify-content-end">
            <div class="pt-1 mr-2">
              <span class="sentiment-score">本文の感情分析スコア<%= @article.score %></span>
              <small>投稿日:<%= @article.created_at.strftime('%Y/%m/%d') %></small>
              <i class="favorite-btn_<%= @article.id %>"><%= render "favorites/favorites", article: @article %></i>
              <i class="far fa-comments ml-1"><%= @article.article_comments.count %></i>
            </div>
          </div>

          <div class="float-right article-button">
            <% if @article.user == current_user %>
              <%= link_to "編集", edit_article_path(@article), class: "btn btn-outline-success" %>
              <%= link_to "削除", article_path(@article), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-outline-primary" %>
            <% end %>
          </div>
        </div>
    </div>
	</div>
</div>

<div class="container">
  <div class="row">
  	<div class="col-8 bg-white rounded article-show">

  		<div class="card my-4">
  			<h5 class="card-header">Comment:</h5>
  		    <div id="comments_error">
            <%= render 'layouts/error_messages', obj: @article_comment %>
          </div>
          <div class="card-body pb-0">
            <div class="form-group pb-3 border-bottom">
              <%= form_with(model:[@article,@article_comment],remote: true) do |f| %>
                <%= f.text_area :comment, rows:'5',placeholder: "コメントしよう！", class: "form-control" %>
                <div class="d-flex justify-content-end mt-2">
                  <%= f.submit "送信する", class: "btn btn-success"%>
                </div>
              <% end %>
  				  </div>
          </div>
  				<div class="media mb-4 ml-2">
           <div class='comment-index'>
              <%= render 'article_comments/article_comments', article: @article %>
           </div>
  				</div>
  			<%= link_to "投稿一覧に戻る", articles_path, class: "btn btn-outline-secondary mt-3 mb-5" %>
  		</div>
    </div>
  </div>
</div>

app/views/favorites/_favorites.html.erb
<%# いいね機能 %>
<% if article.favorited_by?(current_user) %>
  <%= link_to article_favorites_path(article), method: :delete, remote: true do %>
    <i class="fas fa-heart"><%= article.favorites.count %></i>
  <% end %>
<% else %>
  <%= link_to article_favorites_path(article), method: :post, remote: true do %>
    <i class="far fa-heart"><%= article.favorites.count %></i>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$(".favorite-btn_<%= @article.id %>").html("<%= j(render 'favorites', article: @article) %>");

app/views/favorites/destroy.js.erb
$(".favorite-btn_<%= @article.id %>").html("<%= j(render 'favorites', article: @article) %>");

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-5">
      <h2><i class="fas fa-user-edit"></i>プロフィール編集</h2>
      <%= form_with model:@user, local:true do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %><br>
        <input type="submit" name="commit" value="Update User" class="btn btn-success" data-disable-with="Update User">
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-10 offset-md-1 mt-5">
      <h2><i class="fas fa-users"></i>フォロワー一覧</h2>
      <table class="table">
        <thead>
          <tr>
            <th>名前</th>
            <th>紹介文</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.name, user_path(user.id) %></td>
              <td><%= user.introduction %></td>
              <td><%= link_to "プロフィール", user_path(user), class: "btn btn-outline-info" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-10 offset-md-1 mt-5">
      <h2><i class="fas fa-users"></i>フォロー一覧</h2>
      <table class="table">
        <thead>
          <tr>
            <th>名前</th>
            <th>紹介文</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.name, user_path(user) %></td>
              <td><%= user.introduction %></td>
              <td><%= link_to "プロフィール", user_path(user), class: "btn btn-outline-info" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3 mt-5">
      <%= render 'articles/ranking', all_ranks: @all_ranks, one_months_ago_ranks: @one_months_ago_ranks %>
    </div>
    <div class="col-md-8 offset-md-1 mt-5">
      <h2><i class="fas fa-users"></i>ユーザー一覧</h2>
      <table class="table">
        <thead>
          <tr>
            <th>名前</th>
            <th>紹介文</th>
            <th colspan="3"></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.introduction %></td>
              <td>
                <% if current_user != user %>
                  <% if user.followed_by?(current_user) %>
                    <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete, class: "btn btn-secondary"  %></p>
                  <% else %>
                    <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-outline-secondary" %></p>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to "プロフィール", user_path(user), class: "btn btn-outline-info" %></td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
	<div class="success_messages">
		<%= notice %>
	</div>
	<div class="row">
		<div class="col-md-5 mt-5">
			<h2><i class="fas fa-calendar-day"></i>カレンダー</h2>
      <%= month_calendar events: @user.articles do |date, articles| %>
			  <%= date.day %>
			  <% articles.each do |article| %>
			    <div>
			      <%= link_to article.title, article_path(article) %>
			    </div>
			  <% end %>
			<% end %>
 		</div>
 		<div class="col-md-5 offset-md-1 mt-5">
 			<h2><i class="fas fa-house-user"></i>マイページ</h2>
 			<h4>登録情報</h4>
 			<table class="table">
 				<tbody>
 					<tr>
 						<th></th>
 						<th></th>
 					</tr>
 					<tr>
 						<td>名前:<%= @user.name %></td>
 					</tr>
 					<tr>
 						<td>紹介文：<%= @user.introduction %></td>
 					</tr>
 				</tbody>
 			</table>
 			<p>
 				<%= link_to myindex_user_path, class: "btn btn-outline-info" do %>
 					<%= @user.name %>の投稿一覧
 				<% end %>
 			</p>
			<p>
 				<%= link_to "フォロー一覧", follows_user_path(current_user), class: "btn btn-outline-info" %>
 			</p>
 			<p>
 				<%= link_to "フォロワー一覧", followers_user_path(current_user), class: "btn btn-outline-info" %>
 			</p>
 			<p>
 			<% if @user.id == current_user.id %>
			  <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-outline-info" %>
			<% end %>
 			</p>
		</div>
 	</div>
</div>